language: node_js
node_js:
  - "6.9.1"
branches:
  only:
    - master
before_script:
  - npm install -g firebase-tools
script:
  - npm test 
  - npm run build
after_success:
  - firebase deploy --token "$FIREBASE_TOKEN"
