language: node_js
node_js:
  - "6.9.1"
cache: yarn
branches:
  only:
    - master
before_script:
  - yarn global add firebase-tools
script:
  - yarn test
  - yarn run build
after_success:
  - firebase deploy --token "$FIREBASE_TOKEN"
